sudo: false

language: python

python:
  - "3.6"
virtualenv:
  system_site_packages: true

# command to install dependencies
install:
  # - pip install -r requirements.txt
  - pip install -U tox-travis
  - pip install https://github.com/mopidy/mopidy/archive/v3.0.0a6.zip
  - pip install Pykka >= 2.0.1
  - pip install setuptools
  - pip install pyserial
  - pip install transitions
  - pip install podcastparser
  - pip install bcrypt
  - pip install microparcel
  - pip install .

addons:
  apt:
    packages:
      - python3-dev
      - python3-gst-1.0
      - gir1.2-gstreamer-1.0
      - gir1.2-gst-plugins-base-1.0
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-ugly
      - gstreamer1.0-tools

env:
  - TOX_ENV=py36
  - TOX_ENV=flake8

install:
  - "pip install tox"

script:
  - "tox -e $TOX_ENV"

after_success:
  - "if [ $TOX_ENV == 'py36' ]; then pip install coveralls; coveralls; fi"


